services:
  app:
    build: .
    container_name: z360_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - z360

  db:
    image: mysql:8.0
    container_name: z360_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: z-360
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    networks:
      - z360

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Z-360_queue_worker
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
      - db
    networks:
      - z360

volumes:
  db_mysql:

networks:
  z360:
    driver: bridge
